"""HelixDB infrastructure helpers for installed Forensic-Claw builds."""

from __future__ import annotations

import subprocess
from importlib.resources import files
from pathlib import Path
from typing import Literal

import typer
from rich.console import Console

infra_app = typer.Typer(help="Manage optional graph-vector storage infrastructure")
console = Console()
InfraBackend = Literal["helix"]


HELIX_TOML = """[project]
name = "forensic-claw-knowledge"
queries = "./db/"

[local.dev]
port = 6969
build_mode = "dev"
bm25 = true
mcp = false
"""


HELIX_DOCKER_COMPOSE_YAML = """name: forensic-claw-helix

# This compose file starts the HelixDB image generated by `helix build dev`.
# Run `helix check dev` and `helix build dev` first, or use `infra up`.
services:
  app:
    build:
      context: ./.helix/dev
      dockerfile: Dockerfile
    image: helix-forensic-claw-knowledge-dev:dev
    container_name: helix-forensic-claw-knowledge-dev_app
    restart: unless-stopped
    ports:
      - "0.0.0.0:${HELIX_HOST_PORT:-6969}:${HELIX_CONTAINER_PORT:-6969}"
    volumes:
      - ./.helix/.volumes/dev:/data
    environment:
      HELIX_PORT: "${HELIX_CONTAINER_PORT:-6969}"
      HELIX_DATA_DIR: /data
      HELIX_INSTANCE: dev
      HELIX_PROJECT: forensic-claw-knowledge
    networks:
      - forensic-claw-helix

networks:
  forensic-claw-helix:
    driver: bridge
"""


HELIX_README = """# Forensic-Claw HelixDB Backend

This directory is a HelixDB project for the Forensic-Claw knowledge store.

Requirements:
- Docker Desktop
- Helix CLI: curl -sSL https://install.helix-db.com | bash

Forensic-Claw commands:

```powershell
Forensic-Claw.exe infra init --backend helix
Forensic-Claw.exe infra up --backend helix
Forensic-Claw.exe infra status --backend helix
Forensic-Claw.exe infra logs --backend helix
Forensic-Claw.exe infra down --backend helix
```

Manual Docker Compose workflow:

```powershell
helix check dev
helix build dev
docker compose -f docker-compose.yml up -d
docker compose -f docker-compose.yml ps
docker compose -f docker-compose.yml logs -f
docker compose -f docker-compose.yml down
```

Forensic-Claw should point to localhost port 6969 with knowledge.backend = "helix".
"""


HELIX_START_PS1 = """$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root
$LocalHelix = Join-Path $Root "bin\\helix.exe"
$Helix = if (Test-Path $LocalHelix) { $LocalHelix } else { "helix" }

if (-not (Test-Path $LocalHelix) -and -not (Get-Command helix -ErrorAction SilentlyContinue)) {
    Write-Error "Helix CLI was not found. Install it first: curl -sSL https://install.helix-db.com | bash"
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Error "Docker CLI was not found. Start Docker Desktop or install Docker first."
}

& $Helix check dev
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

& $Helix build dev
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

docker compose -f docker-compose.yml up -d
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

docker compose -f docker-compose.yml ps
exit $LASTEXITCODE
"""


HELIX_STOP_PS1 = """param(
    [switch] $DeleteData
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

docker compose -f docker-compose.yml down
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if ($DeleteData) {
    $Volume = Join-Path $Root ".helix\\.volumes\\dev"
    if (Test-Path $Volume) {
        Remove-Item -LiteralPath $Volume -Recurse -Force
    }
}
"""


HELIX_STATUS_PS1 = """$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

docker compose -f docker-compose.yml ps
exit $LASTEXITCODE
"""


HELIX_LOGS_PS1 = """$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

docker compose -f docker-compose.yml logs -f
exit $LASTEXITCODE
"""


def get_default_infra_dir() -> Path:
    """Return the user-scoped infra directory used by installed builds."""
    return Path.home() / ".forensic-claw" / "infra"


def ensure_infra_files(infra_dir: Path | None = None, *, force: bool = False) -> tuple[Path, Path]:
    """Write the default HelixDB project used by installed/native deployments."""
    return ensure_helix_files(infra_dir, force=force)


def ensure_backend_files(
    backend: InfraBackend = "helix",
    infra_dir: Path | None = None,
    *,
    force: bool = False,
) -> tuple[Path, Path]:
    """Write backend-specific infra files for installed/native deployments."""
    if backend != "helix":
        raise ValueError("Only the HelixDB backend is supported.")
    return ensure_helix_files(infra_dir, force=force)


def ensure_helix_files(infra_dir: Path | None = None, *, force: bool = False) -> tuple[Path, Path]:
    """Write the HelixDB project used by installed/native deployments."""
    target_dir = infra_dir or get_default_infra_dir()
    helix_dir = target_dir / "helix"
    db_dir = helix_dir / "db"
    db_dir.mkdir(parents=True, exist_ok=True)

    toml_path = helix_dir / "helix.toml"
    query_path = db_dir / "forensic_claw.hx"
    readme_path = helix_dir / "README.md"
    compose_path = helix_dir / "docker-compose.yml"
    start_path = helix_dir / "start.ps1"
    stop_path = helix_dir / "stop.ps1"
    status_path = helix_dir / "status.ps1"
    logs_path = helix_dir / "logs.ps1"

    if force or not toml_path.exists():
        toml_path.write_text(HELIX_TOML, encoding="utf-8")
    if force or not query_path.exists():
        query_path.write_text(_default_helix_queries(), encoding="utf-8")
    if force or not readme_path.exists():
        readme_path.write_text(HELIX_README, encoding="utf-8")
    if force or not compose_path.exists():
        compose_path.write_text(HELIX_DOCKER_COMPOSE_YAML, encoding="utf-8")
    if force or not start_path.exists():
        start_path.write_text(HELIX_START_PS1, encoding="utf-8")
    if force or not stop_path.exists():
        stop_path.write_text(HELIX_STOP_PS1, encoding="utf-8")
    if force or not status_path.exists():
        status_path.write_text(HELIX_STATUS_PS1, encoding="utf-8")
    if force or not logs_path.exists():
        logs_path.write_text(HELIX_LOGS_PS1, encoding="utf-8")

    return toml_path, readme_path


def _default_helix_queries() -> str:
    """Return the packaged HelixQL query contract."""
    return (
        files("forensic_claw.knowledge")
        .joinpath("helix_queries.hx")
        .read_text(encoding="utf-8")
    )


def _helix_project_dir(infra_dir: Path | None = None) -> Path:
    target_dir = infra_dir or get_default_infra_dir()
    return target_dir / "helix"


def _helix_compose_path(infra_dir: Path | None = None) -> Path:
    return _helix_project_dir(infra_dir) / "docker-compose.yml"


def run_helix(args: list[str], infra_dir: Path | None = None) -> int:
    """Run Helix CLI against the generated Helix project."""
    ensure_helix_files(infra_dir)
    project_dir = _helix_project_dir(infra_dir)
    try:
        result = subprocess.run(["helix", *args], cwd=project_dir, check=False)
    except FileNotFoundError:
        console.print("[red]Helix CLI was not found.[/red] Install it with:")
        console.print("[cyan]curl -sSL https://install.helix-db.com | bash[/cyan]")
        return 127
    return result.returncode


def run_compose(args: list[str], infra_dir: Path | None = None) -> int:
    """Run Docker Compose against the generated Helix compose file."""
    ensure_helix_files(infra_dir)
    project_dir = _helix_project_dir(infra_dir)
    compose_path = _helix_compose_path(infra_dir)
    try:
        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), *args],
            cwd=project_dir,
            check=False,
        )
    except FileNotFoundError:
        console.print("[red]Docker CLI was not found.[/red] Start Docker Desktop first.")
        return 127
    return result.returncode


@infra_app.command("init")
def infra_init(
    path: Path | None = typer.Option(None, "--path", help="Infra directory"),
    backend: InfraBackend = typer.Option(
        "helix",
        "--backend",
        help="helix",
    ),
    force: bool = typer.Option(False, "--force", help="Overwrite generated infra files"),
) -> None:
    """Create storage infrastructure files for installed/native deployments."""
    primary_path, readme_path = ensure_backend_files(backend, path, force=force)
    console.print(f"[green]Infra files ready[/green]: {primary_path}")
    console.print(f"[dim]Backend[/dim]: {backend}")
    console.print(f"[dim]README[/dim]: {readme_path}")


@infra_app.command("up")
def infra_up(
    path: Path | None = typer.Option(None, "--path", help="Infra directory"),
    backend: InfraBackend = typer.Option(
        "helix",
        "--backend",
        help="helix",
    ),
) -> None:
    """Start the selected storage backend."""
    check_code = run_helix(["check", "dev"], path)
    if check_code != 0:
        raise typer.Exit(check_code)
    build_code = run_helix(["build", "dev"], path)
    if build_code != 0:
        raise typer.Exit(build_code)
    code = run_compose(["up", "-d"], path)
    raise typer.Exit(code)


@infra_app.command("down")
def infra_down(
    path: Path | None = typer.Option(None, "--path", help="Infra directory"),
    backend: InfraBackend = typer.Option(
        "helix",
        "--backend",
        help="helix",
    ),
    delete_data: bool = typer.Option(False, "--delete-data", help="Also delete backend data"),
) -> None:
    """Stop storage infrastructure."""
    code = run_compose(["down"], path)
    if code == 0 and delete_data:
        project_dir = _helix_project_dir(path).resolve()
        volume_dir = (project_dir / ".helix" / ".volumes" / "dev").resolve()
        try:
            volume_dir.relative_to(project_dir)
        except ValueError:
            console.print("[red]Refusing to delete data outside the Helix project directory.[/red]")
            raise typer.Exit(1)
        if volume_dir.exists():
            import shutil

            shutil.rmtree(volume_dir)
            console.print(f"[yellow]Deleted Helix data directory[/yellow]: {volume_dir}")
    raise typer.Exit(code)


@infra_app.command("status")
def infra_status(
    path: Path | None = typer.Option(None, "--path", help="Infra directory"),
    backend: InfraBackend = typer.Option(
        "helix",
        "--backend",
        help="helix",
    ),
) -> None:
    """Show status for the storage infrastructure."""
    code = run_compose(["ps"], path)
    raise typer.Exit(code)


@infra_app.command("logs")
def infra_logs(
    path: Path | None = typer.Option(None, "--path", help="Infra directory"),
    backend: InfraBackend = typer.Option(
        "helix",
        "--backend",
        help="helix",
    ),
) -> None:
    """Stream logs for storage infrastructure."""
    code = run_compose(["logs", "-f"], path)
    raise typer.Exit(code)
